### ISSUE TITLE
token

### ISSUE THREAD

**Issue by stalkerj** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#12]
Earlier I scanned token for one of my 4 AC. It's working great.
But now I reinstalled HomeBridge and reinstalled all the plugins. When I'm trying to scan for a new token for another AC that is what I got. What I did wrong?

> pi@raspberry:~ $ homebridge-samsung-ac-get-token 10.0.1.20
> -bash: homebridge-samsung-ac-get-token: command not found

**Comment by SebastianOsinski** [comment]
Are you sure you have installed the plugin? This may indicate that plugin is not installed or not installed properly. What happens when you start homebridge? Is there a line `Loaded plugin: homebridge-plugin-samsung-air-conditioner` in console? You can also run `npm list -g --depth 0`. This will list all npm modules installed globally, `homebridge-plugin-samsung-air-conditioner` should be listed there. If not, install it with `npm install -g homebridge-plugin-samsung-air-conditioner`

**Comment by stalkerj** [comment]
Reinstalled plugin and it’s working.
Sorry for my mistake
