### ISSUE TITLE
Failed authentication

### ISSUE THREAD

**Issue by robertodorta** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#14]
Hi, thanks for the wonderful work you've done with this plugin. I've this problem trying to get the token:

`root@raspberrypi:/home/pi# homebridge-samsung-ac-get-token 192.168.1.137
IP:  192.168.1.137
Power on the device within the next 30 seconds
Error occured: Failed authentication`

I'm using the v2 of the plugin, but I'm getting the same error with the latest non-beta version.

**Comment by SebastianOsinski** [comment]
Hi @robertodorta Your output suggests that connection to AC has been established (as you got 'Power on the device...' message) so that's a good sign. `Failed authentication` is thrown when AC sends a message which indicates you didn't press power button on the remote in that 30 seconds timeframe. At least that's the only case I know of which causes that message to be sent.
