### ISSUE TITLE
Error occured: connect ECONNREFUSED <IP>

### ISSUE THREAD

**Issue by Sardanapo** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#18]
Hi,
I'm getting this error?
MY AC is connected to the same network as my RaspberryPI. Inside my pi I can ping my AC.
AC model:AR12RXWXCWKN

**Comment by SebastianOsinski** [comment]
Hi. I'm not sure about that, but it seems like your model is one of the newer ones which use different communication protocol. My plugin supports older ACs. For newer ones, there is this plugin: https://github.com/cicciovo/homebridge-samsung-airconditioner

**Comment by Wrotaz** [comment]
Hi, 

I'm getting the same error as Sardnanapo. My ACs are working on 2878 port. I'm able to get their tokens and configure config.json (putting IP, MAC, and so on, there). However, when I start Homebridge, I get:

[Klimatyzator] Connecting...                                                                              
[6/16/2019, 12:55:00 PM] [Klimatyzator] Error occured: connect ECONNREFUSED 127.0.0.1:2878                                         
[6/16/2019, 12:55:00 PM] [Klimatyzator] Connection closed because error occured                                                    
[6/16/2019, 12:55:00 PM] [Klimatyzator] Trying to reconnect in 5s...  

I can add Homebridge accessory to Homekit and the ACs are visible, though cannot be controlled (nor the status readouts are right). 

I'm using Homebridge on QNAP, however I also installed it on Ubuntu, and the result is the same. I'm not sure, if the plugin opens the 2878 port on Homebridge machine, as if I check netstat, I get:

Active Internet connections (only servers)                                                                                                                                                                              
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name                                                                                                                        
tcp        0      0 127.0.0.11:42471        0.0.0.0:*               LISTEN      -                                                                                                                                       
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      368/homebridge-conf                                                                                                                     
tcp        0      0 :::51826                :::*                    LISTEN      -                                                                                                                                       
udp        0      0 0.0.0.0:47157           0.0.0.0:*                           -                                                                                                                                       
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -                                                                                                                                       
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -                                                                                                                                       
udp        0      0 127.0.0.11:42323        0.0.0.0:*                           -       

Do you have any idea, what could be wrong? Could I do something to try to debug the problem better?

All the best,

Tomasz

**Comment by SebastianOsinski** [comment]
Hi. Could you share your Config.json here? You can anonymize tokens.

**Comment by Wrotaz** [comment]
Sure, here it goes (I only changed last four characters of tokens to XXXX -- because, maybe I got the tokens wrong...):

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "02:42:C0:1C:7C:D3",
        "port": 51826,
        "pin": "123-45-678"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [
        {
            "accessory": "Samsung Air Conditioner",
            "name": "Klimatyzator - Amelka",
            "ip": "192.168.2.22",
            "token": "b727d2f8-3023-4e41-9020-30d400a0XXXX",
            "mac": "BC:8C:CD:54:E6:FC",
            "log_socket_activity": "true",
            "keep_alive": "false"
        },
        {
            "accessory": "Samsung Air Conditioner",
            "name": "Klimatyzator - Natalka",
            "ip": "192.168.2.23",
            "token": "8576fc21-93ce-4cc3-8640-6099d9efXXXX",
            "mac": "BC:8C:CD:71:98:25",
            "log_socket_activity": "true",
            "keep_alive": "false"
        }
    ],
    "platforms": []
}

```

**Comment by SebastianOsinski** [comment]
You have wrong keys for your air conditioners' ip addresses. It should be `ip_address` instead of `ip` :). In the log you provided, you can see that plugin tries to connect to `127.0.0.1:2878` - plugin does not have AC's IP address and passes `null` to socket library it uses, which then defaults to `127.0.0.1` - localhost address :)

**Comment by Wrotaz** [comment]
Oh my... I'm as much thankful to you as stupid I'm feeling ;-). Thank you very much. I have probably taken a sample config.json from plugin to Samsung ACs listening on port 8888 and haven't cross-checked, if all the keys are the same. And then went to routing territory without looking at basics. 

Everything is now working as a charm. I think that my model is not on the list, so it can be added: AR07HSFSAWKN (internal unit from triple multi-split).

P.S. Baaaardzo dziękuję! Powinno mnie tknąć, że port powinien być po stronie docelowego urządzenia, a nie localhosta. W każdym razie bardzo się cieszę, że działa, bo oryginalna aplikacja samsunga już nie jest utrzymywana i nie dało się spoza domu sterować urządzeniami.
