### ISSUE TITLE
Doesn't work with LibreSSL 2.2.7

### ISSUE THREAD

**Issue by kkoscielniak** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#21]
The `homebridge-samsung-get-ac-token` plugin didn't work on macOS High Sierra with LibreSSL 2.2.7 (I have an instance of `homebridge` on an old Macbook). 

It worked on macOS Mojave with LibreSSL 2.6.5. 

After obtaining AC token with newer LibreSSL and configuring `homebridge` on macOS with LibreSSL 2.2.7 it does not work (there are the same errors as when using `homebridge-samsung-get-ac-token` script. 

Currently installing Mojave to check if it upgrades LibreSSL and move on.

**Comment by kkoscielniak** [comment]
Well, apparently LibreSSL version is not a problem, since after upgrading it, the error persists. 

The error I get is: 
```sh
IP:  192.168.1.xx # the IP adress I provide is correct
Error occured: 4469716416:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1922:
```

**Comment by kkoscielniak** [comment]
Well, I cannot be 100% sure, but I've checked if there are NodeJS versions mismatch between two computers (the one where the plugin didn't work and the one where it did) and I downgraded `node` to 10.16 LTS. Now it works.

**Comment by SebastianOsinski** [comment]
Hi! Thanks for your investigation! I'll try to look into it in spare time. I checked my setup and I am indeed using Node 10.16 (I use https://github.com/oznu/docker-homebridge which I really recommend as it really makes setup easier, especially on RPi, where SD card can fail at any time and you have to setup everything again)

**Comment by rasssta** [comment]
I'm having the same issue with 10.16.3 :/

**Comment by init4** [comment]
Check issue #28  , this sounds like the same problem

**Comment by coniglioemanuele** [comment]
seems all related to ssl as follow:

i got same error on raspian buster after whole upgrading last week end.
error is due to openssl that doesn't support anymore tls1.
to solve i edited manually the plugin in lib/air-conditioner-api.js between line 45-46 add: secureProtocol: 'TLSv1_method',
to get also ac-get-token work i add also in bin/ac-get-token.js

this force connection by tls1, is a workaround, probably best fix is by editing code and manage this option as accessories parameter like tls version

**Comment by coniglioemanuele** [comment]
updated yesterday, it works thanks
